services:
  backend:
    build: ./AnimeGet-Backend
    container_name: anime-backend
    restart: always
    env_file:
      - ./AnimeGet-Backend/.env
    expose:
      - "3000"
    networks:
      - anime-network

  frontend:
    build: ./AnimeGet-Frontend
    container_name: anime-frontend
    restart: always
    ports:
      - "8090:80"
    depends_on:
      - backend
    networks:
      - anime-network

networks:
  anime-network:
    driver: bridge
